version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: fluxlog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fluxlog_erp
      MYSQL_USER: fluxlog_user
      MYSQL_PASSWORD: fluxlog123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fluxlog-network

  adminer:
    image: adminer:latest
    container_name: fluxlog-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - fluxlog-network
    depends_on:
      - mysql

  backend:
    build: ./backend
    container_name: fluxlog-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fluxlog_erp?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=fluxlog_user
      - SPRING_DATASOURCE_PASSWORD=fluxlog123
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    depends_on:
      - mysql
    networks:
      - fluxlog-network

  frontend:
    build: ./frontend
    container_name: fluxlog-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - fluxlog-network
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  fluxlog-network:
    driver: bridge